baseURL = "https://yoichu7.netlify.app/"
title = "yoichu7 - blog"
copyright = "Copyright Â© 2020, yoichu7"
theme = "indigo"
paginate = 100
isCJKLanguage = true
languageCode = "ja-jp"

[params]
  Author = "yoichu7"
  Description = "èª¬æ˜ã ã‚ˆ"
  Subtitle = "æŠ€è¡“ãƒ–ãƒ­ã‚° | netlify"
  Avatar = "images/lily.png"
  Biography = "ã‚½ãƒ•ãƒˆã‚¦ã‚§ã‚¢é–‹ç™ºã—ã¦ã„ã‚‹ãŠã˜ã•ã‚“ã€‚ãƒ†ãƒ¬ãƒ“ã«ã—ã‚ƒã¹ã‚Šã‹ã‘ã¦å®¶æ—ã‹ã‚‰ã†ã–ãŒã‚‰ã‚Œã¦ã„ã‚‹é¡ã€‚"
  ShowBio = false
  PermalinkText = "ğŸ”—"

  # Contact/social-network identifiers for social icons
  # EmailAddress = "email.address@example.com"
  # FacebookUser = "FacebookUserName"
  # FlickrUser = "FlickrUserName"
  GitHubUser = "yoichibeer"
  # GitLabUser = "GitLabUserName"
  # GlitchUser = "GlitchUserName"
  # KeybaseUser = "KeybaseUserName"
  # LinkedInUser = "LinkedInUserName"
  # MediumUser = "MediumUserName"
  # MicroBlogUser = "MicroBlogUserName"
  # RedditUser = "RedditUserName"
  # StackOverflowUser = "StackOverflowUserName"
  # TumblrUser = "TumblrUserName"
  # TwitterUser = "TwitterUserName"
  # InstagramUser = "InstagramUserName"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]
    # EmailAddress = "email.address@example.com"
    # FlickrUser = "FlickrUserName"
    GitHubUser = "yoichibeer"
    # TwitterUser = "TwitterUserName"
    # MicroBlogUser = "MicroBlogUserName"
    Country = "Japan"
    City = "Yokohama"
